### ISSUE TITLE
Unable to restart from the checkpoint

### ISSUE THREAD

**Issue by ghost** [pcingola/BigDataScript#135]
Hello,

I have an issue with restarting from the saved checkpoint. The message error is:

Exception in thread "main" java.lang.RuntimeException: Error replacing fake field 'functionDeclaration' from class 'ca.mcgill.mcb.pcingola.bigDataScript.lang.MethodCall'
    at ca.mcgill.mcb.pcingola.bigDataScript.lang.BigDataScriptNode.replaceFake(BigDataScriptNode.java:595)
    at ca.mcgill.mcb.pcingola.bigDataScript.serialize.BigDataScriptSerializer.parseLines(BigDataScriptSerializer.java:453)
    at ca.mcgill.mcb.pcingola.bigDataScript.serialize.BigDataScriptSerializer.load(BigDataScriptSerializer.java:281)
    at ca.mcgill.mcb.pcingola.bigDataScript.BigDataScript.runCheckpoint(BigDataScript.java:916)
    at ca.mcgill.mcb.pcingola.bigDataScript.BigDataScript.run(BigDataScript.java:883)
    at ca.mcgill.mcb.pcingola.bigDataScript.BigDataScript.main(BigDataScript.java:188)
Caused by: java.lang.RuntimeException: Cannot replace fake node '15178'
    at ca.mcgill.mcb.pcingola.bigDataScript.lang.BigDataScriptNodeFactory.realNode(BigDataScriptNodeFactory.java:220)
    at ca.mcgill.mcb.pcingola.bigDataScript.lang.BigDataScriptNode.replaceFake(BigDataScriptNode.java:586)
    ... 5 more

Not sure if I do something wrong. 

I believe that I use the last version from the github. The .chp file is attached.(I put .txt just to attach it here).

[my.chp.txt](https://github.com/pcingola/BigDataScript/files/321125/my.chp.txt)

Sincerely,
Jurijs

**Comment by pcingola** [comment]
Closing old issues, feel free to re-open.
