### ISSUE TITLE
Exception in thread "main" java.lang.RuntimeException: Cannot cast to 'int' or 'real'

### ISSUE THREAD

**Issue by juanmas07** [pcingola/BigDataScript#160]
I have an issue while running BDS.

I'm using binaries:
```
./files/libs/bds/bds             
Error: Missing program file name.
Bds 0.99999l (build 2017-05-12 14:34), by Pablo Cingolani
```

Enviorment
```
PRETTY_NAME="Debian GNU/Linux 7 (wheezy)"
NAME="Debian GNU/Linux"
VERSION_ID="7"
VERSION="7 (wheezy)"
ID=debian
```
Error:
```
./files/libs/bds/bds pipeline.bds
Exception in thread "main" java.lang.RuntimeException: Cannot cast to 'int' or 'real'. This should never happen!
        at org.bds.lang.ExpressionUnaryMinus.returnType(ExpressionUnaryMinus.java:29)
        at org.bds.lang.ExpressionBinary.returnType(ExpressionBinary.java:52)
        at org.bds.lang.ExpressionAssignment.returnType(ExpressionAssignment.java:29)
        at org.bds.lang.ExpressionWrapper.returnType(ExpressionWrapper.java:39)
        at org.bds.lang.BdsNode.typeCheck(BdsNode.java:797)
        at org.bds.lang.BdsNode.typeChecking(BdsNode.java:816)
        at org.bds.lang.BdsNode.typeChecking(BdsNode.java:828)
        at org.bds.Bds.compile(Bds.java:324)
        at org.bds.Bds.runCompile(Bds.java:862)
        at org.bds.Bds.run(Bds.java:814)
        at org.bds.Bds.main(Bds.java:182)
```

**Comment by juanmas07** [comment]
And I'll answer myself, 

In the code, I was doing:
`cmd **=+** " -out " + gene_sequences + ".db"`
instead of
`cmd **+=** " -out " + gene_sequences + ".db"`

**Comment by pcingola** [comment]
Can you share the code snippet that caused the error? 
I'll try to improve the error message

**Comment by juanmas07** [comment]
it was exactly this:
`cmd =+ " -out " + gene_sequences + ".db"`
where it sould be **+=**

**Comment by pcingola** [comment]
How was 'cmd' defined? how about 'gene_sequences'?

**Comment by juanmas07** [comment]
I'll place the full code here:

```
#required inputs
string reference_sequences = "files/data/Triticum_aestivum.TGACv1.dna.toplevel.fa";
string reference_sequences_chromosomal = "files/output/chromosomal.fa";
string reference_annotations = "files/data/Triticum_aestivum.TGACv1.37.gff3";
string reference_annotations_clean = "files/data/Triticum_aestivum.TGACv1.37.clean.gff3";
string tae = "files/data/TAE.fa.filtered.21.nodups"

#intermediate results
string tae_allhits = "files/output/tae_dna.allhits.csv"
string ann_genes = "files/output/genes.gff3";
string gene_sequences = "files/output/genes_sequences.fasta"
string gene_sequences_db = gene_sequences + ".db";
string sumirfold_res = "files/output/sumirfold.csv";

#helpers
string cmd = "";

#clean gff3 file for pandas
cmd =  "cat " + reference_annotations; 
cmd += " |  sed '/^#/ d' > " + reference_annotations_clean
#stage("clean '#' from reference annotations ",cmd);

#only genes in gff
cmd =  "awk -F '\t' '{ if($3==\"gene\") print}' ";
cmd += " " + reference_annotations_clean  + " > " + ann_genes
#stage("filter gff to only genes ",cmd);

#remove some ids from reference sequence
cmd = "python scripts/FAexclude.py -s " + reference_sequences;
cmd += " -e Pt -e Mt -o " + reference_sequences_chromosomal + "";
#stage("clean reference annotations from mitocondrial DNA",cmd);

#extract genes sequences from reference and annotations +- 100
cmd =  "python scripts/ann2fasta.py -s " + reference_sequences_chromosomal;
cmd += " -a " + ann_genes;
cmd += " -w 150 ";
cmd += " -o " + gene_sequences;
stage("all sequences to genes sequences",cmd);

#makeblastdb dna
cmd = "makeblastdb -dbtype 'nucl' -in " + gene_sequences;
cmd += " -out " + gene_sequences_db
cmd += " -parse_seqids"
stage("makeblastdb for gene sequences", cmd);

#map miRNA sequences into genes sequences
cmd =  "blastn -word_size 21 ";
cmd += " -task blastn-short -query " + tae;
cmd += " -db " + gene_sequences_db; 
cmd += " -ungapped -penalty -1 -reward 1 -outfmt 6 "; 
cmd += " -out " + tae_allhits;
stage("TAE vs GENE_sequences",cmd)

#validate miRNA secondary structure
cmd = "perl scripts/sumirfold.pl ";
cmd += tae;
cmd += " " + tae_allhits + " ";
cmd += " " + gene_sequences_db + " ";
cmd += " > " + sumirfold_res + " ";
stage("sumirfold", cmd);

#extract valid miRNA sequences

#cleavage of targets

#helper functions
void stage(string name, string cmd) {
  print "Stage: " + name + "\n";
  print "Command: " + cmd + "\n";
  sys $cmd;
}

```

**Comment by pcingola** [comment]
OK, fixed, now the error message is:

```
$ ./z.bds
ERROR [ file 'z.bds', line 6 ] :	Cannot cast expression to int or real
```
Thank you
