### ISSUE TITLE
Error with latest commits

### ISSUE THREAD

**Issue by ChiWPak** [pcingola/BigDataScript#167]
Hi Pablo:

With commits 

```
commit 9c7c0b63bf959e6c526eeaf549d84abfe0f00704
Author: pcingola <pablo.e.cingolani@gmail.com>
Date:   Thu Jun 7 11:33:46 2018 -0400

commit 10f6db77a6cb847b60154c0942077510d92ffb95
Author: pcingola <pablo.e.cingolani@gmail.com>
Date:   Thu Jun 7 11:27:49 2018 -0400
```

I'm getting the following error

```
Exception in thread "main" java.lang.RuntimeException: Error getting field 'bdsThread' from class 'org.bds.compile.BdsNodeWalker'
        at org.bds.compile.BdsNodeWalker.findNodes(BdsNodeWalker.java:106)
        at org.bds.compile.BdsNodeWalker.findNodes(BdsNodeWalker.java:77)
        at org.bds.compile.BdsNodeWalker.findNodes(BdsNodeWalker.java:37)
        at org.bds.lang.statement.StatementWithScope.addLocalSymbols(StatementWithScope.java:37)
        at org.bds.lang.statement.StatementWithScope.typeCheck(StatementWithScope.java:69)
        at org.bds.lang.BdsNode.typeChecking(BdsNode.java:698)
        at org.bds.compile.BdsCompiler.typeChecking(BdsCompiler.java:307)
        at org.bds.compile.BdsCompiler.compile(BdsCompiler.java:59)
        at org.bds.run.BdsRun.compileBds(BdsRun.java:169)
        at org.bds.run.BdsRun.compile(BdsRun.java:126)
        at org.bds.run.BdsRun.runCompile(BdsRun.java:422)
        at org.bds.run.BdsRun.run(BdsRun.java:346)
        at org.bds.Bds.run(Bds.java:358)
        at org.bds.Bds.main(Bds.java:51)
Caused by: java.lang.IllegalArgumentException: Can not set org.bds.run.BdsThread field org.bds.lang.ProgramUnit.bdsThread to org.bds.compile.BdsNodeWalker
        at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
        at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
        at sun.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:58)
        at sun.reflect.UnsafeObjectFieldAccessorImpl.get(UnsafeObjectFieldAccessorImpl.java:36)
        at java.lang.reflect.Field.get(Field.java:393)
        at org.bds.compile.BdsNodeWalker.findNodes(BdsNodeWalker.java:90)
        ... 13 more
```

I'm using `java/oracle/jdk1.8.0_65`

**Comment by pcingola** [comment]
Is it working OK now? I think I fixed it.

**Comment by serine** [comment]
Just pulling up on this issue, cause don't want to create new issue. 

I was having issue with tests, one of my test started to fail on `v2.0rc8` release, but tested out on latest commit 9ad04607 and tests are now passing again. 

I was just going to ask if `v2.0.rc9` release coming out soon? 

Thanks

**Comment by ChiWPak** [comment]
Sorry for the late reply - the latest version `Bds 2.0rc9` - seems to work for me now. Thanks again! Will let you know if I run into any other issues with it.

**Comment by serine** [comment]
sounds like this issue have been resolved? can somebody close this issue? manually or through another commit? and new tag pretty please...
