### ISSUE TITLE
A lot of jobs and very fast scheduling system on a cluster

### ISSUE THREAD

**Issue by gusevfe** [pcingola/BigDataScript#38]
Hi.

I am running BigDataScript with on a cluster with TorquePBS installed. When I run a script with ~200 tasks, I run into some exceptions (see below). This does not happen when I reduce the number of tasks.

My guess is that after submitting cluster runs the jobs almost immediately (if there are free nodes) -- if you submit a script with `qsub`, it almost immediately goes to running state. And BigDataScript does not handle this well.

Is it really necessary for tasks to go through all stages? Can something be fixed here?
Thank you in advance.

```
java.lang.RuntimeException: Task: Cannot jump from state 'SCHEDULED' to state 'RUNNING'                                                                                [11370/86673]
'code/venter.bds', line 30
        at ca.mcgill.mcb.pcingola.bigDataScript.task.Task.state(Task.java:653)
        at ca.mcgill.mcb.pcingola.bigDataScript.executioner.Executioner.taskUpdateRunning(Executioner.java:677)
        at ca.mcgill.mcb.pcingola.bigDataScript.executioner.ExecutionerCluster.taskUpdateRunning(ExecutionerCluster.java:310)
        at ca.mcgill.mcb.pcingola.bigDataScript.executioner.Executioner.taskUpdateStates(Executioner.java:713)
        at ca.mcgill.mcb.pcingola.bigDataScript.executioner.Executioner.reportsChecksUpdates(Executioner.java:279)
        at ca.mcgill.mcb.pcingola.bigDataScript.executioner.Executioner.runExecutionerLoop(Executioner.java:401)
        at ca.mcgill.mcb.pcingola.bigDataScript.executioner.Executioner.runExecutioner(Executioner.java:358)
        at ca.mcgill.mcb.pcingola.bigDataScript.executioner.Executioner.run(Executioner.java:342)
java.lang.RuntimeException: Task: Cannot jump from state 'SCHEDULED' to state 'RUNNING'
'code/venter.bds', line 30
        at ca.mcgill.mcb.pcingola.bigDataScript.task.Task.state(Task.java:653)
        at ca.mcgill.mcb.pcingola.bigDataScript.executioner.Executioner.taskUpdateRunning(Executioner.java:677)
        at ca.mcgill.mcb.pcingola.bigDataScript.executioner.ExecutionerCluster.taskUpdateRunning(ExecutionerCluster.java:310)
        at ca.mcgill.mcb.pcingola.bigDataScript.executioner.Executioner.taskUpdateStates(Executioner.java:713)
        at ca.mcgill.mcb.pcingola.bigDataScript.executioner.Executioner.reportsChecksUpdates(Executioner.java:279)
        at ca.mcgill.mcb.pcingola.bigDataScript.executioner.Executioner.runExecutionerLoop(Executioner.java:401)
        at ca.mcgill.mcb.pcingola.bigDataScript.executioner.Executioner.runExecutioner(Executioner.java:358)
        at ca.mcgill.mcb.pcingola.bigDataScript.executioner.Executioner.run(Executioner.java:342)
00:00:00.309    CmdCluster 'venter.bds.20141028_132950_006/task.line_30.id_5': Error killing process 427670
Exception in thread "Thread-64" java.lang.RuntimeException: Task: Cannot jump from state 'SCHEDULED' to state 'RUNNING'
'code/venter.bds', line 30
        at ca.mcgill.mcb.pcingola.bigDataScript.task.Task.state(Task.java:653)
        at ca.mcgill.mcb.pcingola.bigDataScript.executioner.Executioner.taskUpdateRunning(Executioner.java:677)
        at ca.mcgill.mcb.pcingola.bigDataScript.executioner.ExecutionerCluster.taskUpdateRunning(ExecutionerCluster.java:310)
        at ca.mcgill.mcb.pcingola.bigDataScript.executioner.Executioner.taskUpdateStates(Executioner.java:713)
        at ca.mcgill.mcb.pcingola.bigDataScript.executioner.Executioner.reportsChecksUpdates(Executioner.java:279)
        at ca.mcgill.mcb.pcingola.bigDataScript.executioner.Executioner.runExecutionerLoopAfter(Executioner.java:411)
        at ca.mcgill.mcb.pcingola.bigDataScript.executioner.Executioner.runExecutioner(Executioner.java:372)
        at ca.mcgill.mcb.pcingola.bigDataScript.executioner.Executioner.run(Executioner.java:342)
00:00:00.417    CmdCluster 'venter.bds.20141028_132950_006/task.line_30.id_53': Error killing process 427660
00:00:00.423    CmdCluster 'venter.bds.20141028_132950_006/task.line_30.id_54': Error killing process 427659
00:00:00.428    CmdCluster 'venter.bds.20141028_132950_006/task.line_30.id_55': Error killing process 427661
00:00:00.439    CmdCluster 'venter.bds.20141028_132950_006/task.line_30.id_56': Error killing process 427666
00:00:00.449    CmdCluster 'venter.bds.20141028_132950_006/task.line_30.id_57': Error killing process 427664
00:00:00.463    CmdCluster 'venter.bds.20141028_132950_006/task.line_30.id_58': Error killing process 427662
00:00:00.480    CmdCluster 'venter.bds.20141028_132950_006/task.line_30.id_59': Error killing process 427663
00:00:00.487    CmdCluster 'venter.bds.20141028_132950_006/task.line_30.id_60': Error killing process 427665
00:00:00.496    CmdCluster 'venter.bds.20141028_132950_006/task.line_30.id_61': Error killing process 427667
00:00:00.550    CmdCluster 'venter.bds.20141028_132950_006/task.line_30.id_54': Error killing process 427659
00:00:00.560    Error trying to find out post-mortem info on task (PID '427783').
        Exit code : 153
        Stdout    :
        Stderr    :
00:00:00.565    Error trying to find out post-mortem info on task (PID '427783').
        Exit code : 153
        Stdout    :
        Stderr    :
00:00:00.579    Error trying to find out post-mortem info on task (PID '427787').
        Exit code : 153
        Stdout    :
        Stderr    :
00:00:00.585    Error trying to find out post-mortem info on task (PID '427787').
        Exit code : 153
        Stdout    :
        Stderr    :
00:00:00.591    Error trying to find out post-mortem info on task (PID '427793').
        Exit code : 153
        Stdout    :
        Stderr    :
00:00:00.596    Error trying to find out post-mortem info on task (PID '427793').
        Exit code : 153
        Stdout    :
        Stderr    :
00:00:00.603    Error trying to find out post-mortem info on task (PID '427789').
```

**Comment by pcingola** [comment]
I'm closing this issue since the main problem was solved 
and the remaining one has a corresponding feature request.
