### ISSUE TITLE
BDS is getting a runtime exception when I add a specfic task

### ISSUE THREAD

**Issue by golharam** [pcingola/BigDataScript#70]
I'm getting a runtime exception after the AST tree is created.  If I remove the specific task I added, the script runs.  I haven't been able to determine what the problem is.  Can I email you my script so you can see, if that helps?

Exception in thread "main" java.lang.RuntimeException: Error creating object: Class 'ca.mcgill.mcb.pcingola.bigDataScript.lang.Progr
amUnit'
        at ca.mcgill.mcb.pcingola.bigDataScript.lang.BigDataScriptNodeFactory.factory(BigDataScriptNodeFactory.java:129)
        at ca.mcgill.mcb.pcingola.bigDataScript.lang.BigDataScriptNodeFactory.factory(BigDataScriptNodeFactory.java:74)
        at ca.mcgill.mcb.pcingola.bigDataScript.BigDataScript.compile(BigDataScript.java:303)
        at ca.mcgill.mcb.pcingola.bigDataScript.BigDataScript.runCompile(BigDataScript.java:912)
        at ca.mcgill.mcb.pcingola.bigDataScript.BigDataScript.run(BigDataScript.java:864)
        at ca.mcgill.mcb.pcingola.bigDataScript.BigDataScript.main(BigDataScript.java:176)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:80)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:57)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:539)
        at ca.mcgill.mcb.pcingola.bigDataScript.lang.BigDataScriptNodeFactory.factory(BigDataScriptNodeFactory.java:123)
        ... 5 more
Caused by: java.lang.RuntimeException: Error parsing file 'ExomePipeline.bds', line 1, char 18, node ''
        at ca.mcgill.mcb.pcingola.bigDataScript.lang.BigDataScriptNode.doParse(BigDataScriptNode.java:111)
        at ca.mcgill.mcb.pcingola.bigDataScript.lang.ProgramUnit.<init>(ProgramUnit.java:39)
        ... 10 more
Caused by: java.lang.RuntimeException: Error creating object: Class 'ca.mcgill.mcb.pcingola.bigDataScript.lang.StatementExpr'
        at ca.mcgill.mcb.pcingola.bigDataScript.lang.BigDataScriptNodeFactory.factory(BigDataScriptNodeFactory.java:129)
        at ca.mcgill.mcb.pcingola.bigDataScript.lang.BigDataScriptNodeFactory.factory(BigDataScriptNodeFactory.java:74)
        at ca.mcgill.mcb.pcingola.bigDataScript.lang.BigDataScriptNode.factory(BigDataScriptNode.java:126)
        at ca.mcgill.mcb.pcingola.bigDataScript.lang.Block.parse(Block.java:30)
        at ca.mcgill.mcb.pcingola.bigDataScript.lang.ProgramUnit.parse(ProgramUnit.java:53)
        at ca.mcgill.mcb.pcingola.bigDataScript.lang.BigDataScriptNode.doParse(BigDataScriptNode.java:109)
        ... 11 more
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.GeneratedConstructorAccessor5.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:57)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:539)
        at ca.mcgill.mcb.pcingola.bigDataScript.lang.BigDataScriptNodeFactory.factory(BigDataScriptNodeFactory.java:123)
        ... 16 more
Caused by: java.lang.RuntimeException: Error parsing file 'ExomePipeline.bds', line 142, char 0, node 'StatementExpr:NULL'
        at ca.mcgill.mcb.pcingola.bigDataScript.lang.BigDataScriptNode.doParse(BigDataScriptNode.java:111)
        at ca.mcgill.mcb.pcingola.bigDataScript.lang.BigDataScriptNode.<init>(BigDataScriptNode.java:49)
        at ca.mcgill.mcb.pcingola.bigDataScript.lang.Statement.<init>(Statement.java:13)
        at ca.mcgill.mcb.pcingola.bigDataScript.lang.Expression.<init>(Expression.java:16)
        at ca.mcgill.mcb.pcingola.bigDataScript.lang.ExpressionWrapper.<init>(ExpressionWrapper.java:19)
        at ca.mcgill.mcb.pcingola.bigDataScript.lang.StatementExpr.<init>(StatementExpr.java:17)
        ... 20 more
Caused by: java.lang.RuntimeException: Error creating object: Class 'ca.mcgill.mcb.pcingola.bigDataScript.lang.ExpressionTask'
        at ca.mcgill.mcb.pcingola.bigDataScript.lang.BigDataScriptNodeFactory.factory(BigDataScriptNodeFactory.java:129)
        at ca.mcgill.mcb.pcingola.bigDataScript.lang.BigDataScriptNodeFactory.factory(BigDataScriptNodeFactory.java:74)
        at ca.mcgill.mcb.pcingola.bigDataScript.lang.BigDataScriptNode.factory(BigDataScriptNode.java:126)
        at ca.mcgill.mcb.pcingola.bigDataScript.lang.ExpressionWrapper.parse(ExpressionWrapper.java:33)
        at ca.mcgill.mcb.pcingola.bigDataScript.lang.BigDataScriptNode.doParse(BigDataScriptNode.java:109)
        ... 25 more
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:80)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:57)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:539)
        at ca.mcgill.mcb.pcingola.bigDataScript.lang.BigDataScriptNodeFactory.factory(BigDataScriptNodeFactory.java:123)
        ... 29 more
Caused by: java.lang.NullPointerException
        at ca.mcgill.mcb.pcingola.bigDataScript.lang.ExpressionTask.sanityCheck(ExpressionTask.java:235)
        at ca.mcgill.mcb.pcingola.bigDataScript.lang.BigDataScriptNode.doParse(BigDataScriptNode.java:115)
        at ca.mcgill.mcb.pcingola.bigDataScript.lang.BigDataScriptNode.<init>(BigDataScriptNode.java:49)
        at ca.mcgill.mcb.pcingola.bigDataScript.lang.Statement.<init>(Statement.java:13)
        at ca.mcgill.mcb.pcingola.bigDataScript.lang.Expression.<init>(Expression.java:16)
        at ca.mcgill.mcb.pcingola.bigDataScript.lang.ExpressionWithScope.<init>(ExpressionWithScope.java:18)
        at ca.mcgill.mcb.pcingola.bigDataScript.lang.ExpressionTask.<init>(ExpressionTask.java:69)
        ... 34 more

**Comment by pcingola** [comment]
Yes, please send me the file and I'll take a look at it (pablo dot e dot cingolani at gmail)

**Comment by pcingola** [comment]
I haven't received your script...

**Comment by golharam** [comment]
Sorry, just got back from a vacation.  Let me track this down.  I don't
remember which script this was occuring on.

**Comment by pcingola** [comment]
Let me know if you find this issue again, I'm closing it...(looks like it may have already been solved).
