### ISSUE TITLE
java.lang.OutOfMemoryError:

### ISSUE THREAD

**Issue by juanmas07** [pcingola/BigDataScript#84]
I'm getting this when running my pipeline.

Exception in thread "Thread-52" java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3332)
	at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:137)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:121)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:421)
	at java.lang.StringBuffer.append(StringBuffer.java:272)
	at ca.mcgill.mcb.pcingola.bigDataScript.osCmd.StreamGobbler.runLineGobbler(StreamGobbler.java:176)
	at ca.mcgill.mcb.pcingola.bigDataScript.osCmd.StreamGobbler.run(StreamGobbler.java:105)

**Comment by pcingola** [comment]
Can you share send a minimal script that produces the error condition?
Otherwise its going to be quite difficult to debug...

**Comment by juanmas07** [comment]
the script giving me the error is this

cmd = "perl scripts/sumirfold.pl " + tae + ".filtered " + tae + ".filtered.allhits.perfectmatch.splitted.perfectmatch2.selection2 " + scaff_db_ids

it runs the UNAfold software.

I can give you any other information

**Comment by pcingola** [comment]
You are not redirecting STDOUT/STDERR to a file. Does this 
perl script produce too much of sdtout/stderr?

**Comment by juanmas07** [comment]
Yes it dotes produce a lote of output

**Comment by pcingola** [comment]
Consider redirecting the output of your command (i.e. within your 'sys') to a file or to dev/null of you don't need it.

**Comment by juanmas07** [comment]
excellent thank you
