### ISSUE TITLE
Cannot execute commnads: 'qstat'

### ISSUE THREAD

**Issue by leepc12** [pcingola/BigDataScript#98]
I recently moved to a new cluster with sun grid engine. I have a superuser privilege so I tried to make the sge settings similar to the old sge cluster. BDS works flawlessly on the old sge server. BDS and bds.config is installed locally on $HOME/.bds. I checked that pidRegex works fine.

```
sge.pe = shm
sge.mem = h_vmem
sge.timeout = h_rt
taskShell = /bin/bash -e
sysShell = /bin/bash -e -c
pidRegex = "Your job (\\S+)"
waitAfterTaskRun = 5000
clusterRunAdditionalArgs = -v PATH=/home/leepc12/.bds
```

```
#!/usr/bin/env bds

task( taskName := "test nandi", cpus := 1, timeout := 600, mem := 1000000000 ) {
        sys export PATH=$PATH:/bin
        sys sleep 1; echo test > output
}
```

I also tested running a script without BDS (test.sh). It worked fine.

```
#!/bin/bash
sleep 1; echo test > output
```

```
qsub -pe shm 1 test.sh
```

When I try the following command
```
$bds -l -v -d -noRmOnExit -s sge test.bds
```

I got the following error. 
```
$ qstat -j 410
==============================================================
job_number:                 410
exec_file:                  job_scripts/410
submission_time:            Thu May 21 09:34:49 2015
owner:                      leepc12
uid:                        1040
group:                      users
gid:                        100
sge_o_home:                 /home/leepc12/
sge_o_log_name:             leepc12
sge_o_path:                 /software/java/latest/bin:/usr/local/ncbi/sra-tools/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/opt/caffe/python:/home/leepc12/.bds
sge_o_shell:                /bin/bash
sge_o_workdir:              /home/leepc12/work/pe_test
sge_o_host:                 nandi
account:                    sge
stderr_path_list:           NONE:NONE:/home/leepc12/work/pe_test/test.bds.20150521_093449_420/task.test.test_nandi.line_4.id_1.stderr.cluster
hard resource_list:         h_rt=660,h_vmem=1000000000
mail_list:                  leepc12@nandi
notify:                     FALSE
job_name:                   STDIN
stdout_path_list:           NONE:NONE:/home/leepc12/work/pe_test/test.bds.20150521_093449_420/task.test.test_nandi.line_4.id_1.stdout.cluster
jobshare:                   0
env_list:                   PATH=/home/leepc12/.bds
script_file:                STDIN
parallel environment:  shm range: 1
error reason    1:          05/21/2015 09:35:03 [1040:34268]: execvlp(/var/spool/gridengine/execd/nandi/job_scripts/410, "/var/s
scheduling info:            Job is in error state
```

```
$ tail /var/spool/gridengine/execd/nandi/messages 
05/21/2015 09:35:04|  main|nandi|E|shepherd of job 410.1 exited with exit status = 27
05/21/2015 09:35:04|  main|nandi|E|can't open usage file "active_jobs/410.1/usage" for job 410.1: No such file or directory
05/21/2015 09:35:04|  main|nandi|E|05/21/2015 09:35:03 [1040:34268]: execvlp(/var/spool/gridengine/execd/nandi/job_scripts/410, "/var/spool/gridengine/execd/nandi/job_scripts/410") failed: Exec format error
```

I searched about "failed: Exec format error", it turns out to be shell definition problem (first line of shell script). So I am using "unix_behavior" in my sge queue setting.

```
$ bds -l -v -d -noRmOnExit -s sge test.bds
Picked up _JAVA_OPTIONS: -Xms256M -Xmx512M -XX:ParallelGCThreads=1
00:00:00.000	BigDataScript 0.999k (build 2015-05-14), by Pablo Cingolani
00:00:00.005	BigDataScript: Initialize global scope.
00:00:00.030	BigDataScript: Initialize standard libraries.
00:00:00.048	BigDataScript: Native library:
NativeLibraryFunctions:
	FunctionNativePrint
	FunctionNativePrintErr
	FunctionNativeMinInt
	FunctionNativeMaxInt
	FunctionNativeMinReal
	FunctionNativeMaxReal
	FunctionNativeRand
	FunctionNativeRandInt
	FunctionNativeRandIntRange
	FunctionNativeRandSeed
	FunctionNativeRangeInt
	FunctionNativeRangeIntStep
	FunctionNativeRangeReal
	FunctionNativeSleep
	FunctionNativeSleepReal
	FunctionNativeToIntFromBool
	FunctionNativeToIntFromReal
	FunctionNativeConfig
	FunctionNativeConfigOri

00:00:00.077	BigDataScript: Native library:
NativeLibraryString:
	MethodNative_string_length
	MethodNative_string_toUpper
	MethodNative_string_toLower
	MethodNative_string_trim
	MethodNative_string_substr_start_end
	MethodNative_string_substr_start
	MethodNative_string_split_regex
	MethodNative_string_lines
	MethodNative_string_isEmpty
	MethodNative_string_startsWith_str
	MethodNative_string_endsWith_str
	MethodNative_string_indexOf_str
	MethodNative_string_lastIndexOf_str
	MethodNative_string_replace_str1_str2
	MethodNative_string_parseInt
	MethodNative_string_parseReal
	MethodNative_string_parseBool
	MethodNative_string_replace_regex_repl
	MethodNative_string_path
	MethodNative_string_baseName
	MethodNative_string_baseName_ext
	MethodNative_string_dirName
	MethodNative_string_pathName
	MethodNative_string_extName
	MethodNative_string_canRead
	MethodNative_string_canWrite
	MethodNative_string_canExec
	MethodNative_string_exists
	MethodNative_string_isDir
	MethodNative_string_isFile
	MethodNative_string_delete
	MethodNative_string_rm
	MethodNative_string_mkdir
	MethodNative_string_read
	MethodNative_string_removeExt
	MethodNative_string_removeExt_ext
	MethodNative_string_rmOnExit
	MethodNative_string_swapExt_extNew
	MethodNative_string_swapExt_extOld_extNew
	MethodNative_string_write_str
	MethodNative_string_readLines
	MethodNative_string_chdir
	MethodNative_string_dir
	MethodNative_string_dir_regex
	MethodNative_string_dirPath
	MethodNative_string_dirPath_regex
	MethodNative_string_size
	MethodNative_string_isDone
	MethodNative_string_isDoneOk
	MethodNative_string_stdout
	MethodNative_string_stderr
	MethodNative_string_exitCode

00:00:00.087	Parsing
00:00:00.087	BigDataScript: Loading file: 'test.bds'
00:00:00.088	BigDataScript: Creating AST.
00:00:00.383	AST:
		Child 0:	[28]	Tree:'([28] \n \n \n)'
		Child 1:	[34]	Tree:'([34] ([339 34] task ( ([438 339 34] taskName := ([379 438 339 34] "test nandi")) , ([440 339 34] cpus := ([379 440 339 34] 1)) , ([440 339 34] timeout := ([379 440 339 34] 600)) , ([440 339 34] mem := ([379 440 339 34] 1000000000)) ) ([450 339 34] { ([107 450 339 34] ([353 107 450 339 34] \n)) ([107 450 339 34] ([339 107 450 339 34] sys export PATH=$PATH:/bin) ([340 107 450 339 34] \n)) ([107 450 339 34] ([339 107 450 339 34] sys sleep 1; echo test > output) ([340 107 450 339 34] \n)) })) ([340 34] \n \n \n))'
00:00:00.386	BigDataScript: Creating BigDataScript tree.
00:00:00.415	BigDataScript: AST:
task( taskName := "test nandi", cpus := 1, timeout := 600, mem := 1000000000 ) {
	sys export PATH=$PATH:/bin
	sys  sleep 1; echo test > output
}

00:00:00.415	BigDataScript: Type checking.
00:00:00.420	Initializing
00:00:00.436	Process ID: test.bds.20150521_093449_420
00:00:00.437	Running
00:00:00.440	ExpressionTask (test.bds:4) : Task dependency check (needsUpdate=true): (  )
00:00:00.447	Executioner factory: Creating new executioner type 'SGE'
00:00:00.468	Config: Parsing 'clusterRunAdditionalArgs'. Number of additional arguments: 2
			0	'-v'
			1	'PATH=/home/leepc12/.bds'
00:00:00.469	ExecutionerClusterSge 'ClusterSge[9]': Using pidRegex 'Your job (\S+)'
00:00:00.471	ExecutionerClusterSge 'ClusterSge[9]': Using pidRegex 'Your job (\S+)'
00:00:00.471	ExecutionerClusterSge 'ClusterSge[9]': Queuing task: test.bds.20150521_093449_420/task.test.test_nandi.line_4.id_1
00:00:00.471	ExecutionerClusterSge 'ClusterSge[9]': Started running
00:00:00.473	BdsThread finished: test.bds.20150521_093449_420
00:00:00.473	Program 'test.bds.20150521_093449_420' execution finished
00:00:00.473	Waiting for all tasks to finish.
00:00:00.474	Wait: Waiting for task to finish: test.bds.20150521_093449_420/task.test.test_nandi.line_4.id_1, state: SCHEDULED
00:00:00.475	ExecutionerClusterSge 'ClusterSge[9]': Selected task:
	task ID        : test.bds.20150521_093449_420/task.test.test_nandi.line_4.id_1
	task hint      :  export PATH=/software/java/latest/bin:/usr/local/ncbi/sra-tools/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/loca
	task resources : cpus: 1	mem: 953.7 MB	timeout: 600	wall-timeout: 86400
	host           : localhost
	host resources : cpus: 2147483647	mem: 8192.0 PB
00:00:00.475	ExecutionerClusterSge 'ClusterSge[9]': Task selected 'test.bds.20150521_093449_420/task.test.test_nandi.line_4.id_1' on host 'localhost'
00:00:00.476	Config: Setting 'maxThreads' to 512
00:00:00.479	Task: Saving file '/home/leepc12/work/pe_test/test.bds.20150521_093449_420/task.test.test_nandi.line_4.id_1.sh'
00:00:00.480	ExecutionerClusterSge 'ClusterSge[9]': Running task test.bds.20150521_093449_420/task.test.test_nandi.line_4.id_1
00:00:00.481	ExecutionerClusterSge 'ClusterSge[9]': Running task test.bds.20150521_093449_420/task.test.test_nandi.line_4.id_1, command:
	echo "bds exec 600 '/home/leepc12/work/pe_test/test.bds.20150521_093449_420/task.test.test_nandi.line_4.id_1.stdout' '/home/leepc12/work/pe_test/test.bds.20150521_093449_420/task.test.test_nandi.line_4.id_1.stderr' '/home/leepc12/work/pe_test/test.bds.20150521_093449_420/task.test.test_nandi.line_4.id_1.exitCode' '/home/leepc12/work/pe_test/test.bds.20150521_093449_420/task.test.test_nandi.line_4.id_1.sh' " | qsub -v PATH=/home/leepc12/.bds -pe shm 1 -l h_vmem=1000000000 -l h_rt=00:11:00 -o /home/leepc12/work/pe_test/test.bds.20150521_093449_420/task.test.test_nandi.line_4.id_1.stdout.cluster -e /home/leepc12/work/pe_test/test.bds.20150521_093449_420/task.test.test_nandi.line_4.id_1.stderr.cluster 
00:00:00.482	Config: Setting 'waitAfterTaskRun' to 5000
00:00:00.486	CmdCluster 'test.bds.20150521_093449_420/task.test.test_nandi.line_4.id_1': Start
00:00:00.486	CmdLocal: Executing  qsub -v PATH=/home/leepc12/.bds -pe shm 1 -l h_vmem=1000000000 -l h_rt=00:11:00 -o /home/leepc12/work/pe_test/test.bds.20150521_093449_420/task.test.test_nandi.line_4.id_1.stdout.cluster -e /home/leepc12/work/pe_test/test.bds.20150521_093449_420/task.test.test_nandi.line_4.id_1.stderr.cluster
00:00:00.509	CmdCluster 'test.bds.20150521_093449_420/task.test.test_nandi.line_4.id_1': Reading PID line 'Your job 410 ("STDIN") has been submitted'
00:00:00.510	ExecutionerClusterSge 'ClusterSge[9]': Regex 'Your job (\S+)' (pidRegex) matched '410' in line: 'Your job 410 ("STDIN") has been submitted'
00:00:00.510	CmdCluster 'test.bds.20150521_093449_420/task.test.test_nandi.line_4.id_1': Running
00:00:00.511	CmdCluster 'test.bds.20150521_093449_420/task.test.test_nandi.line_4.id_1': Done
00:00:05.483	ExecutionerClusterSge 'ClusterSge[9]': Task started 'test.bds.20150521_093449_420/task.test.test_nandi.line_4.id_1'
00:00:05.483	ExecutionerClusterSge 'ClusterSge[9]': Task running 'test.bds.20150521_093449_420/task.test.test_nandi.line_4.id_1'
00:00:05.484	TaskLogger: Appending to PidFile 'bds.pid.34209', lines:
		|410	+	qdel

00:00:05.486	Tail: Adding (TailFileMulti) '/home/leepc12/work/pe_test/test.bds.20150521_093449_420/task.test.test_nandi.line_4.id_1.stdout'
00:00:05.486	Tail: Adding (TailFileMulti) '/home/leepc12/work/pe_test/test.bds.20150521_093449_420/task.test.test_nandi.line_4.id_1.stderr'
00:00:05.487	MonitorTask: Adding task test.bds.20150521_093449_420/task.test.test_nandi.line_4.id_1
00:00:05.488	ExecutionerClusterSge 'ClusterSge[9]': CheckTasksRunningCluster:Config parameter 'pidRegexCheckTaskRunning' not set.
00:00:05.488	ExecutionerClusterSge 'ClusterSge[9]': CheckTasksRunningCluster:Using 'cmdPidColumn' 0
00:00:05.489	ExecutionerClusterSge 'ClusterSge[9]': Queue: No task to run.
00:01:06.520	ExecutionerClusterSge 'ClusterSge[9]': Tasks [ClusterSge[9]]		Pending : 0	Running: 1	Done: 0
		| PID | Task state        | Task name  | Dependencies | Task definition                                                                                                                                        | 
		| --- | ----------------- | ---------- | ------------ | ------------------------------------------------------------------------------------------------------------------------------------------------------ | 
		| 410 | running (RUNNING) | test nandi |              |  export PATH=/software/java/latest/bin:/usr/local/ncbi/sra-tools/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/loca | 

java.lang.RuntimeException: Cannot execute commnads: 'qstat'
	at ca.mcgill.mcb.pcingola.bigDataScript.osCmd.Exec.run(Exec.java:80)
	at ca.mcgill.mcb.pcingola.bigDataScript.osCmd.Exec.exec(Exec.java:37)
	at ca.mcgill.mcb.pcingola.bigDataScript.executioner.CheckTasksRunning.runCommand(CheckTasksRunning.java:226)
	at ca.mcgill.mcb.pcingola.bigDataScript.executioner.CheckTasksRunning.check(CheckTasksRunning.java:80)
	at ca.mcgill.mcb.pcingola.bigDataScript.executioner.Executioner.reportsChecksUpdates(Executioner.java:313)
	at ca.mcgill.mcb.pcingola.bigDataScript.executioner.Executioner.runExecutionerLoop(Executioner.java:409)
	at ca.mcgill.mcb.pcingola.bigDataScript.executioner.Executioner.runExecutioner(Executioner.java:383)
	at ca.mcgill.mcb.pcingola.bigDataScript.executioner.Executioner.run(Executioner.java:367)
00:01:06.524	ExecutionerClusterSge 'ClusterSge[9]': Killed
00:01:06.525	ExecutionerClusterSge 'ClusterSge[9]': Killing task 'test.bds.20150521_093449_420/task.test.test_nandi.line_4.id_1'
00:01:06.526	ExecutionerClusterSge 'ClusterSge[9]': Task finished 'test.bds.20150521_093449_420/task.test.test_nandi.line_4.id_1'
00:01:06.526	Tail: Removing (TailFileMulti) '/home/leepc12/work/pe_test/test.bds.20150521_093449_420/task.test.test_nandi.line_4.id_1.stdout'
00:01:06.527	Tail: Removing (TailFileMulti) '/home/leepc12/work/pe_test/test.bds.20150521_093449_420/task.test.test_nandi.line_4.id_1.stderr'
00:01:06.528	TaskLogger: Appending to PidFile 'bds.pid.34209', lines:
		|410	-

00:01:06.529	MonitorTask: Removing task test.bds.20150521_093449_420/task.test.test_nandi.line_4.id_1
Exception in thread "Thread-1" java.lang.RuntimeException: Cannot execute commnads: 'qstat -f -j 410'
	at ca.mcgill.mcb.pcingola.bigDataScript.osCmd.Exec.run(Exec.java:80)
	at ca.mcgill.mcb.pcingola.bigDataScript.osCmd.Exec.exec(Exec.java:37)
	at ca.mcgill.mcb.pcingola.bigDataScript.executioner.ExecutionerCluster.postMortemInfo(ExecutionerCluster.java:343)
	at ca.mcgill.mcb.pcingola.bigDataScript.executioner.Executioner.taskUpdateFinished(Executioner.java:717)
	at ca.mcgill.mcb.pcingola.bigDataScript.executioner.Executioner.taskUpdateStates(Executioner.java:778)
	at ca.mcgill.mcb.pcingola.bigDataScript.executioner.Executioner.reportsChecksUpdates(Executioner.java:304)
	at ca.mcgill.mcb.pcingola.bigDataScript.executioner.Executioner.runExecutionerLoopAfter(Executioner.java:436)
	at ca.mcgill.mcb.pcingola.bigDataScript.executioner.Executioner.runExecutioner(Executioner.java:397)
	at ca.mcgill.mcb.pcingola.bigDataScript.executioner.Executioner.run(Executioner.java:367)
Task failed:
	Program & line     : 'test.bds', line 4
	Task Name          : 'test nandi'
	Task ID            : 'test.bds.20150521_093449_420/task.test.test_nandi.line_4.id_1'
	Task PID           : '410'
	Task hint          : ' export PATH=/software/java/latest/bin:/usr/local/ncbi/sra-tools/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/loca'
	Task resources     : 'cpus: 1	mem: 953.7 MB	timeout: 600	wall-timeout: 86400'
	State              : 'KILLED'
	Dependency state   : 'ERROR'
	Retries available  : '1'
	Input files        : '[]'
	Output files       : '[]'
	Script file        : '/home/leepc12/work/pe_test/test.bds.20150521_093449_420/task.test.test_nandi.line_4.id_1.sh'
	Exit status        : '3'
	Program            : 
		
		# SYS command. line 5
		
		 export PATH=/software/java/latest/bin:/usr/local/ncbi/sra-tools/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/opt/caffe/python:/home/leepc12/.bds:/bin
		
		# SYS command. line 6
		
		 sleep 1; echo test > output

00:01:06.754	Wait: Task 'test.bds.20150521_093449_420/task.test.test_nandi.line_4.id_1' finished.
00:01:06.754	Writing report file 'test.bds.20150521_093449_420.report.html'
00:01:06.840	Creating DAG summary script 'test.bds.20150521_093449_420.dag.js'
00:01:06.845	Program 'test.bds.20150521_093449_420' finished, run state: 'FINISHED', exit value: 1, tasks executed: 1, tasks failed: 1, tasks failed names: test nandi.
00:01:06.846	Finished. Exit code: 1
00:01:06.847	ExecutionerClusterSge 'ClusterSge[9]': Killed
00:01:06.847	Tail: Killed
00:01:06.848	Tail: Closing.
```

I also tried 
```
$ bds exec 600 '/home/leepc12/work/pe_test/test.bds.20150521_093449_420/task.test.test_nandi.line_4.id_1.stdout' '/home/leepc12/work/pe_test/test.bds.20150521_093449_420/task.test.test_nandi.line_4.id_1.stderr' '/home/leepc12/work/pe_test/test.bds.20150521_093449_420/task.test.test_nandi.line_4.id_1.exitCode' '/home/leepc12/work/pe_test/test.bds.20150521_093449_420/task.test.test_nandi.line_4.id_1.sh'
34396
```

But when I try
```
echo "bds exec 600 '/home/leepc12/work/pe_test/test.bds.20150521_093449_420/task.test.test_nandi.line_4.id_1.stdout' '/home/leepc12/work/pe_test/test.bds.20150521_093449_420/task.test.test_nandi.line_4.id_1.stderr' '/home/leepc12/work/pe_test/test.bds.20150521_093449_420/task.test.test_nandi.line_4.id_1.exitCode' '/home/leepc12/work/pe_test/test.bds.20150521_093449_420/task.test.test_nandi.line_4.id_1.sh' " | qsub -v PATH=/home/leepc12/.bds -pe shm 1 -l h_vmem=1000000000 -l h_rt=00:11:00 -o /home/leepc12/work/pe_test/test.bds.20150521_093449_420/task.test.test_nandi.line_4.id_1.stdout.cluster -e /home/leepc12/work/pe_test/test.bds.20150521_093449_420/task.test.test_nandi.line_4.id_1.stderr.cluster
```

I get exactly same error with different job id.

The followings are my sge settings:

```
ge.pe = shm
sge.mem = h_vmem
sge.timeout = h_rt
taskShell = /bin/bash -e
sysShell = /bin/bash -e -c
pidRegex = "Your job (\\S+)"
waitAfterTaskRun = 5000
clusterRunAdditionalArgs = -v PATH=/home/leepc12/.bds
```

```
$qconf -sconf

execd_spool_dir              /var/spool/gridengine/execd
mailer                       /usr/bin/mail
xterm                        /usr/bin/xterm
load_sensor                  none
prolog                       none
epilog                       none
shell_start_mode             posix_compliant
login_shells                 bash,sh,ksh,csh,tcsh
min_uid                      0
min_gid                      0
user_lists                   none
xuser_lists                  none
projects                     none
xprojects                    none
enforce_project              false
enforce_user                 auto
load_report_time             00:00:40
max_unheard                  00:05:00
reschedule_unknown           00:00:00
loglevel                     log_warning
administrator_mail           root
set_token_cmd                none
pag_cmd                      none
token_extend_time            none
shepherd_cmd                 none
qmaster_params               none
execd_params                 ENABLE_ADDGRP_KILL=true
reporting_params             accounting=true reporting=false \
                             flush_time=00:00:15 joblog=false sharelog=00:00:00
finished_jobs                100
gid_range                    65400-65500
max_aj_instances             2000
max_aj_tasks                 75000
max_u_jobs                   4000
max_jobs                     40000
auto_user_oticket            0
auto_user_fshare             0
auto_user_default_project    none
auto_user_delete_time        86400
delegated_file_staging       false
reprioritize                 0
rlogin_daemon                /usr/sbin/sshd -i
rlogin_command               /usr/bin/ssh
qlogin_daemon                /usr/sbin/sshd -i
qlogin_command               /usr/share/gridengine/qlogin-wrapper
rsh_daemon                   /usr/sbin/sshd -i
```

```
$ qconf -sq main.q_bash

qname                 main.q_bash
hostlist              @allhosts
seq_no                0
load_thresholds       np_load_avg=1.75
suspend_thresholds    NONE
nsuspend              1
suspend_interval      00:05:00
priority              0
min_cpu_interval      00:05:00
processors            UNDEFINED
qtype                 BATCH INTERACTIVE
ckpt_list             NONE
pe_list               shm
rerun                 FALSE
slots                 24,[nandi=23]
tmpdir                /tmp
shell                 /bin/bash
prolog                NONE
epilog                NONE
shell_start_mode      unix_behavior
starter_method        NONE
suspend_method        NONE
resume_method         NONE
terminate_method      NONE
notify                00:00:60
owner_list            NONE
user_lists            NONE
xuser_lists           NONE
subordinate_list      NONE
complex_values        NONE
projects              NONE
xprojects             NONE
calendar              NONE
initial_state         disabled
s_rt                  INFINITY
h_rt                  INFINITY
s_cpu                 INFINITY
h_cpu                 INFINITY
s_fsize               INFINITY
h_fsize               INFINITY
s_data                INFINITY
h_data                INFINITY
s_stack               INFINITY
h_stack               INFINITY
s_core                INFINITY
h_core                INFINITY
s_rss                 INFINITY
h_rss                 INFINITY
s_vmem                INFINITY
h_vmem                INFINITY
```

```
$ qconf -sp shm

pe_name            shm
slots              999
user_lists         NONE
xuser_lists        NONE
start_proc_args    /bin/true
stop_proc_args     /bin/true
allocation_rule    $pe_slots
control_slaves     FALSE
job_is_first_task  FALSE
urgency_slots      min
accounting_summary FALSE
```

```
$ which qstat
/usr/bin/qstat

$ ll /usr/bin/qstat
lrwxrwxrwx 1 root root 38 Mar 11  2014 /usr/bin/qstat -> ../share/gridengine/gridengine-wrapper*

$ cat /usr/bin/../share/gridengine/gridengine-wrapper 
#!/bin/sh

# SGE Wrapper script to ensure correct environment variables are set

set -e

# For each of SGE_ROOT, SGE_CELL:
# 1) If the environment variable is set; use it
# 2) If not, look in /etc/default/gridengine
# 3) If still nothing, fall back to Debian defaults

DEFAULT_SGE_ROOT=/var/lib/gridengine
DEFAULT_SGE_CELL=default
CONFIG_PATH=/etc/default/gridengine
PROG=`basename $0`

# Save environment variables if we have been given them
# so we can restore them at the end
if [ ! -z "${SGE_ROOT}" ]; then
    _SAVED_SGE_ROOT="${SGE_ROOT}"
fi

if [ ! -z "${SGE_CELL}" ]; then
    _SAVED_SGE_CELL="${SGE_CELL}"
fi

# Read from our config file, this will set SGE_ROOT and/or SGE_CELL if
# appropriate

if [ -r "${CONFIG_PATH}" ]; then
    . "${CONFIG_PATH}"
fi

# If we still don't have anything set, fall back to the Debian defaults
if [ -z "${SGE_ROOT}" ]; then
    SGE_ROOT="${DEFAULT_SGE_ROOT}"
fi

if [ -z "${SGE_CELL}" ]; then
    SGE_CELL="${DEFAULT_SGE_CELL}"
fi

# If we had some environment variables, these should override
# anything else we were given so clobber it all again

if [ ! -z "${_SAVED_SGE_ROOT}" ]; then
    SGE_ROOT="${_SAVED_SGE_ROOT}"
fi

if [ ! -z "${_SAVED_SGE_CELL}" ]; then
    SGE_CELL="${_SAVED_SGE_CELL}"
fi

unset _SAVED_SGE_ROOT _SAVED_SGE_CELL

# Make sure we've exported the variables we need to
export SGE_ROOT SGE_CELL

exec /usr/lib/gridengine/${PROG} "$@"
```

**Comment by pcingola** [comment]
I'll try to take a look at this when I get back (I'm out of town now).
Yours

     Pablo

**Comment by leepc12** [comment]
If I specify the script for qsub instead of using STDIN (bds exec). it works.

'''
$qsub -v PATH=/home/leepc12/.bds -pe shm 1 -l h_vmem=1000000000 -l h_rt=00:11:00 -o /home/leepc12/work/pe_test/test.bds.20150521_093449_420/task.test.test_nandi.line_4.id_1.stdout.cluster -e /home/leepc12/work/pe_test/test.bds.20150521_093449_420/task.test.test_nandi.line_4.id_1.stderr.cluster /home/leepc12/work/pe_test/test.bds.20150521_093449_420/task.test.test_nandi.line_4.id_1.sh
```

I will check $HOME/.bds is in my PATH for non-login shells. Does BDS create non-login shells to run cluster commands?

**Comment by leepc12** [comment]
If I replace the following line 
```
			pb.directory(new File(BigDataScriptThreads.getInstance().get().getCurrentDir()));
```
with the exact directory where bds is executed.
```
			pb.directory(new File("/home/leepc12/work/pe_test"));
```
It worked.

calling BigDataScriptThreads.getInstance().get() was okay but calling BigDataScriptThreads.getInstance().get().getCurrentDir() gets crashed. 

So my ad hoc fix for this is...
```
			pb.directory(new File(System.getProperty("user.dir")));
```

I will just stick to this solution until you look into this.

Thanks

**Comment by leepc12** [comment]
I am debugging this error and found that thread id doesn't match. I added some functions to check thread id. Please see the following:

In run/BigDataScriptThreads.java
```
        public void add(BigDataScriptThread bdsThread) {
                long id = Thread.currentThread().getId();
                bdsThreadByThreadId.put(id, bdsThread);
                Timer.showStdErr("DEBUG_JIN: Thread has been added ("+id+"), # of thr =" + bdsThreadByThreadId.size());
        }

        /**
         * Get bdsThread
         */
        public BigDataScriptThread get() {
                long id = Thread.currentThread().getId();
                return bdsThreadByThreadId.get(id);
        }

        public long getId() {
                return Thread.currentThread().getId();
        }

        public long getIdSize() {
                return bdsThreadByThreadId.size();
        }

        /**
         * Remove a bdsThread
         */
        public void remove(BigDataScriptThread bdsThread) {
                long id = Thread.currentThread().getId();
                if (bdsThreadByThreadId.get(id) == bdsThread) bdsThreadByThreadId.remove(id);
                Timer.showStdErr("DEBUG_JIN: Thread has been removed ("+id+"), # of thr =" + bdsThreadByThreadId.size());
        }

        @Override
        public String toString() {
                StringBuilder sb = new StringBuilder();
                for (Long thid : bdsThreadByThreadId.keySet())
                        sb.append(thid + "\t" + bdsThreadByThreadId.get(thid).getBdsThreadId() + "\n");
                return sb.toString();
        }
```

In osCmd/Exec.java
```
                        ProcessBuilder pb = new ProcessBuilder(args);

                        // Make sure we use thread's current directory
                        Timer.showStdErr("DEBUG_JIN: current thread id =" + BigDataScriptThreads.getInstance().getId());

                        //pb.directory(new File(BigDataScriptThreads.getInstance().get().getCurrentDir()));
                        pb.directory(new File(System.getProperty("user.dir")));
 
```

My test.bds
```
#!/usr/bin/env bds

task {
        sys echo "sleep for 60 secs (task1)"
        sys sleep 60
}
```
```
$ ~/.bds/bds -v -s sge test.bds
Picked up _JAVA_OPTIONS: -Xms256M -Xmx512M -XX:ParallelGCThreads=1
00:00:00.000    BigDataScript 0.999l (build 2015-06-04), by Pablo Cingolani
00:00:00.104    Parsing
00:00:00.330    Initializing
00:00:00.341    Process ID: test.bds.20150607_102324_511
00:00:00.341    Running
00:00:00.343    DEBUG_JIN: Thread has been added (8), # of thr =1
00:00:00.348    Executioner factory: Creating new executioner type 'SGE'
00:00:00.355    ExecutionerClusterSge 'ClusterSge[9]': Queuing task: test.bds.20150607_102324_511/task.test.line_4.id_1
00:00:00.355    ExecutionerClusterSge 'ClusterSge[9]': Started running
00:00:00.356    Program 'test.bds.20150607_102324_511' execution finished
00:00:00.357    Waiting for all tasks to finish.
00:00:00.357    Wait: Waiting for task to finish: test.bds.20150607_102324_511/task.test.line_4.id_1, state: SCHEDULED
00:00:00.358    ExecutionerClusterSge 'ClusterSge[9]': Task selected 'test.bds.20150607_102324_511/task.test.line_4.id_1' on host 'localhost'
sleep for 60 secs (task1)
00:01:01.394    DEBUG_JIN: current thread id =9
00:01:01.937    ExecutionerClusterSge 'ClusterSge[9]': Tasks [ClusterSge[9]]            Pending : 0     Running: 1      Done: 0
                | PID  | Task state        | Task name             | Dependencies | Task definition                            |
                | ---- | ----------------- | --------------------- | ------------ | ------------------------------------------ |
                | 1243 | running (RUNNING) | task.test.line_4.id_1 |              | echo "sleep for 60 secs (task1)"; sleep 60 |

00:01:13.639    Wait: Task 'test.bds.20150607_102324_511/task.test.line_4.id_1' finished.
00:01:13.639    Writing report file 'test.bds.20150607_102324_511.report.html'
00:01:13.730    Program 'test.bds.20150607_102324_511' finished, exit value: 0, tasks executed: 1, tasks failed: 0, tasks failed names: .
00:01:13.730    DEBUG_JIN: Thread has been removed (8), # of thr =0
00:01:13.731    Finished. Exit code: 0
00:01:13.732    ExecutionerClusterSge 'ClusterSge[9]': Killed
```

If you look at the above log, thread 8 is created and added to BigDataScriptThreads but why is it changed to 9 after than?

**Comment by pcingola** [comment]
Interesting. I'll need some time to go over all this and get back to you.
Thank you for your detailed explanation!

**Comment by pcingola** [comment]
Hi Jin, looking into the code I realized that the Executioned thread is always sunning on a separate thread:

    public abstract class Executioner extends Thread ...

... and that is thread number 9 in your logs:

    00:00:00.355    ExecutionerClusterSge 'ClusterSge[9]': Queuing task: test.bds.20150607_102324_511/task.test.line_4.id_1

What I'm not getting is how is that affecting your 'qstat' command....

**Comment by leepc12** [comment]
Let me explain this.

There are two threads (id 8 and 9). Thread-8 (BigDataScriptThread) is created in BigDataScriptThreads and is registered in its hashmap. But thread-9 (Exec) is created (when new Exec) to run commands like "qstat" and it is not registered in BigDataScriptThreads' hashmap.

But the following line is executed in osCmd/Exec.java (hence in thread-9). So Thread.currentThread in BigDataScriptThreads class (see code for BigDataScriptThreads.getInstance().get() ) will return thread-9. not thread-8. This is the main reason for the problem. And thread-9 is not registered in the hashmap of BigDataScriptThreads. BigDataScriptThreads.getInstance().get() cannot find "current" thread so it returns null. and seg. fault occurs. 

```
pb.directory(new File(BigDataScriptThreads.getInstance().get().getCurrentDir()));
```

**Comment by pcingola** [comment]
Although I'm still not sure why I'm not seeing the error on my cluster, I've been able to replicate the problem with the code you sent me, thank you.
I think I fixed it now, please let me know if it pops up again.

**Comment by leepc12** [comment]
Thanks this works!
